services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer

    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/bitforge/homelab/data/portainer:/data

    networks:
      - proxy
      - portainer

    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.bitforge`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls=true
      - traefik.http.services.portainer.loadbalancer.server.port=9000

networks:
  proxy:
    external: true

  portainer:
    name: portainer
