services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped

    volumes:
      - ../../data/uptime-kuma:/app/data

    dns:
      - 192.168.0.165

    networks:
      - proxy
      - uptime-kuma

    deploy:
      replicas: 1
      labels:
        - traefik.enable=true

        - traefik.http.routers.uptime.rule=Host(`uptime.bitforge`)
        - traefik.http.routers.uptime.entrypoints=websecure
        - traefik.http.routers.uptime.tls=true
        - traefik.http.routers.uptime.priority=10
        - traefik.http.routers.uptime.middlewares=authentik-forwardauth@swarm

        - traefik.http.services.uptime.loadbalancer.server.port=3001
      update_config:
        order: start-first
        failure_action: rollback
        monitor: 15s
      rollback_config:
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  proxy:
    external: true
    name: proxy-swarm

  uptime-kuma:
    name: uptime-kuma-swarm
