services:
  promtail:
    image: grafana/promtail:3.6.11
    container_name: promtail
    restart: unless-stopped

    command: -config.file=/etc/promtail/config.yml

    volumes:
      - ./config.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ../../data/promtail:/data

    networks:
      - proxy

networks:
  proxy:
    external: true
